Prefix: "&6[UsefulCommands]&r "
PermissionMessage: "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
Broadcast:
  - ""
  - "&7[&cBroadcast&7]&r <broadcast-message>"
  - ""
LeaveOnVanish: true