name: UsefulCommands
version: '${project.version}'
main: com.github.treesontop.usefulcommands.UsefulCommands
api-version: 13
softdepend: [LuckPerms]
commands:
  fly:
    description: toggles flight for a player
    usage: /fly [player]
  reload:
    description: reloads the plugins config
    usage: /reload
  broadcast:
    description: broadcasts a message to all players
    usage: /broadcast <message>
    aliases: [bc]
  heal:
    description: heals a player
    usage: /heal [player]
  feed:
    description: feeds a player
    usage: /feed [player]
  clearchat:
    description: clears the chat
    usage: /clearchat
  enderchest:
    description: opens the enderchest of a player
    usage: /enderchest [player]
    aliases: [ec, echest]