name: UsefulCommands
version: "${project.version}"
main: com.github.treesontop.usefulcommands.UsefulCommands
api-version: 1.13
softdepend: [ LuckPerms ]
commands:
  fly:
    description: toggles flight for a player
    usage: /fly [player]
    permission: usefulcommands.fly
  reload:
    description: reloads the plugins config
    usage: /reload
    permission: usefulcommands.reload
  broadcast:
    description: broadcasts a message to all players
    usage: /broadcast <message>
    aliases: [ bc ]
    permission: usefulcommands.broadcast
  heal:
    description: heals a player
    usage: /heal [player]
    permission: usefulcommands.heal
  feed:
    description: feeds a player
    usage: /feed [player]
    permission: usefulcommands.feed
  clearchat:
    description: clears the chat
    usage: /clearchat
    permission: usefulcommands.clearchat
  enderchest:
    description: opens the enderchest of a player
    usage: /enderchest [player]
    aliases: [ ec, echest ]
    permission: usefulcommands.enderchest
  repair:
    description: repairs a player's item
    usage: /repair
    permission: usefulcommands.repair
    aliases: [ repairall, fixall, fix ]
  suicide:
    description: kills the player
    usage: /suicide
    permission: usefulcommands.suicide
    aliases: [ kms ]
  speed:
    description: edits the player's speed
    usage: /speed <number || player> [number]
    permission: usefulcommands.speed
    aliases: [ flyspeed, fs, walkspeed, ws ]
  kickall:
    description: Kicks all players from the server
    usage: /kickall
    permission: usefulcommands.kickall
    aliases: [ kicka ]
  tpall:
    description: Tps all players of the server to you
    usage: /tpall
    permission: usefulcommands.tpall
  gma:
    description: Sets a player's gamemode to adventure mode
    usage: /gma [player]
    permission: usefulcommands.gma
  gms:
    description: Sets a player's gamemode to survival mode
    usage: /gms [player]
    permission: usefulcommands.gms
  gmc:
    description: Sets a player's gamemode to creative mode
    usage: /gmc [player]
    permission: usefulcommands.gmc
  gmsp:
    description: Sets a player's gamemode to spectator mode
    usage: /gmsp [player]
    ermission: usefulcommands.gmsp
  tempban:
    description: Bans a player temporarily
    usage: /tempban <player> <duration> [reason]