name: UsefulCommands
version: "${project.version}"
main: com.github.treesontop.usefulcommands.UsefulCommands
api-version: 1.13
softdepend: [ LuckPerms ]
permissions:
  usefulcommands.fly.others:
    description: allows you to toggle flight for other players
  usefulcommands.heal.others:
    description: allows you to heal other players
  usefulcommands.feed.others:
    description: allows you to feed other players
  usefulcommands.gamemode.others:
    description: allows you to change the gamemode of other players
  usefulcommands.enderchest.others:
    description: allows you to open the enderchest of other players
  usefulcommands.speed.others:
    description: allows you to change the speed of other players

commands:
  fly:
    description: toggles flight for a player
    usage: /fly [player]
    permission: usefulcommands.fly
  reload:
    description: reloads the plugins config
    usage: /reload
    permission: usefulcommands.reload
  broadcast:
    description: broadcasts a message to all players
    usage: /broadcast <message>
    aliases: [ bc ]
    permission: usefulcommands.broadcast
  heal:
    description: heals a player
    usage: /heal [player]
    permission: usefulcommands.heal
  feed:
    description: feeds a player
    usage: /feed [player]
    permission: usefulcommands.feed
  clearchat:
    description: clears the chat
    usage: /clearchat
    permission: usefulcommands.clearchat
  enderchest:
    description: opens the enderchest of a player
    usage: /enderchest [player]
    aliases: [ ec, echest ]
    permission: usefulcommands.enderchest
  repair:
    description: repairs a player's item
    usage: /repair
    permission: usefulcommands.repair
    aliases: [ repairall, fixall, fix ]
  suicide:
    description: kills the player
    usage: /suicide
    permission: usefulcommands.suicide
    aliases: [ kms ]
  speed:
    description: edits the player's speed
    usage: /speed <number || player> [number]
    permission: usefulcommands.speed
    aliases: [ flyspeed, fs, walkspeed, ws ]
  kickall:
    description: Kicks all players from the server
    usage: /kickall
    permission: usefulcommands.kickall
    aliases: [ kicka ]
  tpall:
    description: Tps all players of the server to you
    usage: /tpall
    permission: usefulcommands.tpall
  gma:
    description: Sets a player's gamemode to adventure mode
    usage: /gma [player]
    permission: usefulcommands.gma
    aliases: [ gamemodea, gmadventure ]
  gms:
    description: Sets a player's gamemode to survival mode
    usage: /gms [player]
    permission: usefulcommands.gms
    aliases: [ gamemodes, gmsurvival ]
  gmc:
    description: Sets a player's gamemode to creative mode
    usage: /gmc [player]
    permission: usefulcommands.gmc
    aliases: [ gamemodec, gmcreative ]
  gmsp:
    description: Sets a player's gamemode to spectator mode
    usage: /gmsp [player]
    permission: usefulcommands.gmsp
    aliases: [ gamemodesp, gmspectator ]
  tempban:
    description: Bans a player temporarily
    usage: /tempban <player> <duration> [reason]
    permission: usefulcommands.tempban
  mute:
    description: mutes a player
    usage: /mute <time || player> [time]
    permission: usefulcommands.mute
